name: mink
description: Mink Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_dotenv: ^6.0.1
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.2.0
  riverpod_annotation: ^4.0.2
  supabase_flutter: ^2.12.4
  url_launcher: ^6.3.0
  phosphor_flutter: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/env/.env
    - assets/env/.env.example
    - assets/images/mink_logo.png
    - assets/images/mink-hi.PNG
    - assets/images/mink-love.PNG
    - assets/images/mink-funny.PNG
    - assets/images/mink-sad.PNG
    - assets/images/mink-cry.PNG
    - assets/images/mink-angry.PNG
    - assets/images/mink-indifferent.PNG
    - assets/icons/phosphor/currency-coin.svg
    - assets/icons/phosphor/currency-diamond.svg
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka/static/Fredoka-Light.ttf
          weight: 300
        - asset: assets/fonts/fredoka/static/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/fredoka/static/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/fredoka/static/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/fredoka/static/Fredoka-Bold.ttf
          weight: 700
